#!/usr/bin/env bash

RED='\033[0;31m'
NC='\033[0m' # No Color

error_message() {
    echo -e "${RED}Error: ${1}${NC}"
}

# Create a regex for a conventional commit.
convetional_commit_regex="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z \-]+\))?!?: .+$"

# Get the commit message (the parameter we're given is just the path to the
# temporary file which holds the message).
commit_message=$(cat "$1")

if [[ "$commit_message" =~ $convetional_commit_regex ]]; then
   echo -e "Commit message meets Conventional Commit standards..."
   exit 0
fi

error_message "The commit message does not meet the Conventional Commit standard"
echo "An example of a valid message is: "
echo "  feat(login): add the 'remember me' button"
echo "More details at: https://www.conventionalcommits.org/en/v1.0.0/#summary"
exit 1