---
{{- if index .Values "monitoring" "enabled" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-monitor
  labels:
    release: {{ .Release.Name }}
spec:
  jobLabel: {{ .Release.Name }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}  # Ensure this matches the app's label
  endpoints:
    - port: http # Name of the port defined in your app's service
      path: /actuator/prometheus
      interval: 30s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}