---
{{- if index .Values "global" "external-secrets" "enabled" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-registry-secret
spec:
  #refreshInterval: 15s
  target:
    name: docker-registry-secret
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: ""
      type: Opaque
      data:
        docker-username: |-
          {{ `{{ .username }}` }}
        docker-password: |-
          {{ `{{ .password }}` }}
        docker-email: |-
          {{ `{{ .email }}` }}
        docker-server: |-
          {{ `{{ .server }}` }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: docker_registry
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: docker_registry
        property: password
    - secretKey: email
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: docker_registry
        property: email
    - secretKey: server
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: docker_registry
        property: server
{{- end }}