---
server:
  port: 8881
spring:
  application:
    name: app2-development-prototype-microservice
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
## configuration for spring actuator
management:
  endpoints:
    enabled-by-default: true # set to false to disable all endpoints
    web:
      exposure:
        include: health,info,metrics
logging:
  level:
    org:
      springframework:
        boot.autoconfigure: WARN
        security: WARN